name: Percy snapshot.
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Install  npm
        run: npm install
      - name: Image resize
        run: npm run resize-images
      - name: project watch
        run: npm run build
      - name: Percy Test
        uses: percy/exec-action@master
        with:
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        