name: Percy snapshot.
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install  npm packages
        run: npm install
      - name: Image resize
        run: npm run resize-images
      - name: Project build
        run: npm run build
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        